name: CI with digger terra

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed, opened, synchronize, reopened ]
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:

  #lint-terraform:
  #  name: Lint
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3

  build:
    runs-on: ubuntu-latest
    permissions:    
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
    steps:
      - name: run-digger
        uses: diggerhq/digger@v0.2.4
        with:
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          digger-token: ${{ secrets.DIGGER_TOKEN }}
          digger-organisation: ${{ secrets.DIGGER_ORGANISATION }}
          digger-hostname: https://cloud.uselemon.cloud/   
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DIGGER_GITHUB_TOKEN: ${{ secrets.DIGGER_GITHUB_TOKEN }}